# Generated by Django 3.2.6 on 2021-12-04 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.TextField(blank=True, null=True)),
                ('technology', models.TextField(blank=True, null=True)),
                ('company', models.TextField(blank=True, null=True)),
                ('startDate', models.TextField(blank=True, null=True)),
                ('endDate', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('experience_lvl', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
